package com.gem.sistema.util;

// TODO: Auto-generated Javadoc
/**
 * The Class Constants.
 *
 * @author Juan Carlos Pedraza Alcala
 */
public class Constants {
	
	/**  Consante para indicar la unidad. */
	public static final int ONE = 1;
	
	/**  Consante para indicar el cero. */
	public static final int ZERO = 0;
	
	/**  Consante para indicar el dos. */
	public static final int TWO = 2;
	
	/**  Consante para indicar el 3. */
	public static final int THREE = 3;
	
	/**  Consante para indicar el 4. */
	public static final int FOUR = 4;
	
	/**  Consante para indicar el 5. */
	public static final int FIVE = 5;
	
	/**  COnstante del 6 WTF. */
	public static final int SIX = 6;
	
	
	/**  COnstante del 7 WTF. */
	public static final int SEVEN = 7;
	
	/**  COnstante del 8 WTF. */
	public static final int EIGHT = 8;
	
	/**  COnstante del 9 WTF. */
	public static final int NINE = 9;
	

	/** Constante para indicar el 3. */
	public static final int MIN_LENTGTH_CLVDEP = 3;
	
	/**  Consante para indicar el cero. */
	public static final int ROUNDING_TWO = 2;

	/**  Prefijo de los metodos set. */
	public static final String PREFIX_SET = "set";
	
	/**  Prefijo de los metodos set. */
	public static final String SEPARATOR_FILE_SYSTEM_DIR = "/";
	
	/** Extension de los archivos de texto plano.
	 */
	public static final String TXT_EXTENSION = ".txt";
	
	/** Extension de los archivos de texto plano.
	 */
	public static final String CSV_EXTENSION = ".csv";
	
	/** Prefijo get.
	 */
	public static final String PREFIX_GET = "get";
	
	/** Espacio en blanco.
	 */
	public static final String BLANK = " ";
	
	/**  Cadena vacia. */
	public static final String EMPTY = "";

	/**  Variable clausula WHERE en los reportes. */
	public static final String PARAMETER_WHERE_CLAUSE = "pWhereClause";
	
	/**  Operador SQL LIKE. */
	public static final String LIKE = " LIKE ";

	/**  Cualificador like. */
	public static final String QUALIFIER_LIKE = "%";
	
	/**  Consante para cuenta contable egresos 51. */
	public static final String ACCOUNT_EXPEDITURE_51 = "51";
	
	/**  Consante para cuenta contable egresos 52. */
	public static final String ACCOUNT_EXPEDITURE_52 = "52";
	
	/**  Consante para cuenta contable egresos 53. */
	public static final String ACCOUNT_EXPEDITURE_53 = "53";
	
	/**  Consante para cuenta contable egresos 54. */
	public static final String ACCOUNT_EXPEDITURE_54 = "54";
	
	/**  Consante para cuenta contable egresos 56. */
	public static final String ACCOUNT_EXPEDITURE_56 = "56";
	
	/**  Consante para cuenta contable egresos 57. */
	public static final String ACCOUNT_EXPEDITURE_57 = "57";
	
	/**  Consante para cuenta contable egresos 57. */
	public static final String ACCOUNT_EXPEDITURE_BUDGET_82 = "82";
	
	/** Constante para indicar el cero string. */
	public static final String STRING_ZERO = "0";
	
	/** Constante para indicar el uno string. */
	public static final String STRING_ONE = "1";
	
	/** Constante para indicar el dos string. */
	public static final String STRING_TWO = "2";
	
	/** Constante para indicar el tres string. */
	public static final String STRING_THREE = "3";
	
	/** Constante para indicar el cuatro string. */
	public static final String PREFIX_ACCOUNT_MAJOR = "4";
	
	/** Constante para indicar el cinco string. */
	public static final String STRING_FIVE = "5";
	
	/** Constante para indicar el tres string. */
	public static final String STRING_SIX = "6";
	
	/** Constante para indicar el seven string. */
	public static final String STRING_SEVEN = "7";
	
	/** Constante para indicar el ocho string. */
	public static final String STRING_EIGHT = "8";
	
	/** Constante para indicar el nueve string. */
	public static final String STRING_NINE = "9";
		
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 51. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8211 = "8211";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8221. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8221 = "8221";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8241. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8241 = "8241";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8251. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8251 = "8251";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8271. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8271 = "8271";
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 52. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8212 = "8212";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8222. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8222 = "8222";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8242. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8242 = "8242";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8252. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8252 = "8252";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8272. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8272 = "8272";
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 53. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8213 = "8213";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8223. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8223 = "8223";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8243. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8243 = "8243";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8253. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8253 = "8253";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8273. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8273 = "8273";
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 54. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8214 = "8214";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8224. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8224 = "8224";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8244. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8244 = "8244";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8254. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8254 = "8254";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8274. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8274 = "8274";
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 56. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8215 = "8215";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8225. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8225 = "8225";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8245. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8245 = "8245";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8255. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8255 = "8255";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8275. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8275 = "8275";
	
	/**  Cuentas presupuestales autogeneradas para la cuenta mayor 57. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8216 = "8216";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8226. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8226 = "8226";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8246. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8246 = "8246";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8256. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8256 = "8256";
	
	/** The Constant ACCOUNT_AUTOGENERATED_BUDGET_8276. */
	public static final String ACCOUNT_AUTOGENERATED_BUDGET_8276 = "8276";
	
	/**  Cuentas presupuestales autogeneradas por una cuenta contable ingreos. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8110 = "8110";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8120. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8120 = "8120";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8130. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8130 = "8130";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8140. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8140 = "8140";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8150. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8150 = "8150";
	
	/**  Cuentas presupuestales autogeneradas por una cuenta presupuestal egresos. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8227 = "8227";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8247. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8247 = "8247";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8257. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8257 = "8257";
	
	/** The Constant ACCOUNT_AUTOGENERATED_INCOME_8277. */
	public static final String ACCOUNT_AUTOGENERATED_INCOME_8277 = "8277";
	
	/** The min length field campo8 matrix indicators. */
	public static int MIN_LENGTH_FIELD_CAMPO8_MATRIX_INDICATORS = 8;
	
	/** The min length field campo8 indicators. */
	public static int MIN_LENGTH_FIELD_CAMPO8_INDICATORS = 10;

	/** The Constant EOL. */
	public static final String EOL="\r\n";
	
	/** The Constant MAX_LENGTH_cta. */
	public static final int MAX_LENGTH_cta = 4;
	
	/** The Constant MAX_LENGTH_clvfte. */
	public static final int MAX_LENGTH_clvfte = 20;
	
	/** The Constant MAX_LENGTH_capfuen. */
	public static final int MAX_LENGTH_capfuen = 20;
	
	/** The Constant MAX_LENGTH_nombref. */
	public static final int MAX_LENGTH_nombref = 140;
	
	/** The Constant MAX_LENGTH_liga. */
	public static final int MAX_LENGTH_liga = 6;
	
	/** The Constant CTA_NO_DELETE_REGEXP. */
	public static final String CTA_NO_DELETE_REGEXP = "(821(1|2|3|4|5|6))|(822(1|2|3|4|5|6|7))|(824(1|2|3|4|5|6|7))|(825(1|2|3|4|5|6|7))|(81(10|20|30|40|50|60|70))|(827(1|2|3|4|5|6|7))";
	
	public static final String TITLES_EJERCIDO = "PROGRAMA, DESCRIPCIÓN, CAP. 1000, CAP 2000, CAP 3000, CAP 4000, CAP 5000, CAP 6000, CAP 7000, CAP 8000, CAP 9000";
	public static final String APPLICCTION_CSV =  "application/csv; charset=UTF-8";
	public static final String APPLICCTION_TXT =  "application/txt; charset=UTF-8";
	public static final String SEPARADOR = " - ";
}
